<?php
/**
 * View script to display the index page
 * 
 * @category    MVCLite
 * @package     App
 * @subpackage  View_Scripts
 * @since       File available since release 1.0.1
 * @author      Cory Collier <corycollier@corycollier.com>
 */
?>

<div class="markup-record">
    <p class="changeable amount">
        <input type="text" name="amount" class="input-amount" value="150" />
    </p>
    <p class="changeable units">
        <input type="text" name="units" class="input-units" value="$" />
    </p>
    <a href="#" class="modify-rule add">Add Rule</a>
</div>

<div class="template rule-template">
    <!-- Channel -->
    <div class="select-value changeable markup-channel">
        <input type="text" name="markup-channel" placeholder="select channel" />
        <ul class="select-options">
            <li><a href="#">Expedia</a></li>
            <li><a href="#">Orbitz</a></li>
            <li><a href="#">Priceline</a></li>
            <li><a href="#">Expedia</a></li>
        </ul>
    </div>
    
    <!-- markup type -->
    <div class="select-value changeable markup-type">
        <input type="text" name="markup-type" placeholder="select markup type" />
        <ul class="select-options">
            <li><a href="#">addition</a></li>
            <li><a href="#">subtraction</a></li>
        </ul>
    </div>
    
    <!--  markup amount -->
    <div class="changeable markup-amount">
        <input type="text" name="markup-amount" value="" placeholder="enter markup amount" />
    </div>
    
    <!--  markup amount -->
    <div class="select-value changeable markup-units">
        <input type="text" name="markup-units" placeholder="select markup units" />
        <ul class="select-options">
            <li><a href="#">%</a></li>
            <li><a href="#">$</a></li>
        </ul>
    </div>
    
    <a href="#" class="modify-rule edit">x</a>
    <a href="#" class="modify-rule save">x</a>
    <a href="#" class="modify-rule remove">x</a>
</div>