<?php
/**
 * Default layout script
 * 
 * @category    MVCLite
 * @package     App
 * @subpackage  View_Layouts
 * @since       File available since release 1.0.1
 * @author      Cory Collier <corycollier@corycollier.com>
 */
?>
<!doctype html>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <title><?php echo @$title; ?></title>
        
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="/favicon.ico">
        <link rel="apple-touch-icon" href="/apple-touch-icon.png">
        
        <link rel="stylesheet" type="text/css" href="/css/reset.css" />
        <link rel="stylesheet" type="text/css" href="/css/style.css" />
    </head>
    <body>
        <header>
            <h1><?php echo @$title; ?></h1>
        </header>
        <nav>
        </nav>
        <section class="content">
            <?php echo @$content; ?>
        </section>
        <footer>
        </footer>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <script src="/js/modernizr-1.7.min.js"></script>
<!--[if lt IE 7 ]>
        <script src="js/libs/dd_belatedpng.js"></script>
        <script>DD_belatedPNG.fix("img, .png_bg");</script>
<![endif]-->
        
    </body>
</html>
